version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "11000:8000"


  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "11001:5432"

